const productos = [
    { id: 1, nombre: "Lirio blanco", imagen: "img/lirio_blanco.jpg", descripcion: "Flor en forma de campana de color blanco, con un gran aroma y detalles delicados. Ideal para bodas y eventos especiales.", precio: 10.00, stock: 20 },
    { id: 2, nombre: "Rosa roja", imagen: "img/rosa_roja.jpg", descripcion: "Rosa clásica de pétalos aterciopelados de color rojo intenso. Símbolo del amor y la pasión.", precio: 12.50, stock: 30 },
    { id: 3, nombre: "Tulipán amarillo", imagen: "img/tulipan_amarillo.jpg", descripcion: "Flor de tallo largo y pétalos amarillos vibrantes, perfecta para alegrar cualquier espacio.", precio: 8.00, stock: 25 },
    { id: 4, nombre: "Margarita blanca", imagen: "img/margarita_blanca.jpg", descripcion: "Flor sencilla y alegre de pétalos blancos y centro amarillo, símbolo de pureza.", precio: 6.00, stock: 50 },
    { id: 5, nombre: "Orquídea morada", imagen: "img/orquidea_morada.jpg", descripcion: "Flor exótica con pétalos de color morado vibrante y detalles delicados, ideal para decoración.", precio: 18.00, stock: 15 },
    { id: 6, nombre: "Girasol", imagen: "img/girasol.jpg", descripcion: "Flor grande de pétalos amarillos que sigue la luz del sol. Perfecta para ambientes cálidos y alegres.", precio: 14.00, stock: 10 },
    { id: 7, nombre: "Clavel rosa", imagen: "img/clavel_rosa.jpg", descripcion: "Flor tradicional con pétalos rizados y color rosa suave. Ideal para regalos y arreglos florales.", precio: 7.50, stock: 40 },
    { id: 8, nombre: "Peonía blanca", imagen: "img/peonia_blanca.jpg", descripcion: "Flor grande y fragante con pétalos blancos delicados. Ideal para centros de mesa elegantes.", precio: 20.00, stock: 12 },
    { id: 9, nombre: "Azucena roja", imagen: "img/azucena_roja.jpg", descripcion: "Flor de pétalos rojos vibrantes y un aroma embriagador, perfecta para regalar.", precio: 16.00, stock: 18 },
    { id: 10, nombre: "Jazmín", imagen: "img/jazmin.jpg", descripcion: "Pequeña flor blanca con un aroma dulce y delicado, ideal para infusiones o decoración.", precio: 5.00, stock: 60 },
    { id: 11, nombre: "Rosa amarilla", imagen: "img/rosa_amarilla.jpg", descripcion: "Rosa de pétalos amarillos brillantes, símbolo de amistad y alegría. Ideal para regalar.", precio: 12.00, stock: 25 },
  { id: 12, nombre: "Clavel blanco", imagen: "img/clavel_blanco.jpg", descripcion: "Flor tradicional con pétalos blancos puros, perfecta para eventos elegantes y arreglos florales.", precio: 7.00, stock: 35 },
  { id: 13, nombre: "Dalia roja", imagen: "img/dalia_roja.jpg", descripcion: "Flor exuberante de pétalos rojos profundos, ideal para decoraciones sofisticadas.", precio: 15.00, stock: 20 },
  { id: 14, nombre: "Lavanda", imagen: "img/lavanda.jpg", descripcion: "Flor aromática de color púrpura, conocida por sus propiedades relajantes y decorativas.", precio: 8.00, stock: 40 },
  { id: 15, nombre: "Hortensia azul", imagen: "img/hortensia_azul.jpg", descripcion: "Flor de gran tamaño con pétalos azul pastel, ideal para bodas y eventos formales.", precio: 18.00, stock: 12 },
  { id: 16, nombre: "Magnolia blanca", imagen: "img/magnolia_blanca.jpg", descripcion: "Flor elegante con pétalos blancos y un aroma suave, símbolo de pureza.", precio: 22.00, stock: 15 },
  { id: 17, nombre: "Crisantemo amarillo", imagen: "img/crisantemo_amarillo.jpg", descripcion: "Flor vibrante con pétalos amarillos en capas, perfecta para alegrar cualquier espacio.", precio: 10.00, stock: 30 },
  { id: 18, nombre: "Amapola roja", imagen: "img/amapola_roja.jpg", descripcion: "Flor delicada de pétalos rojos intensos, símbolo de pasión y fuerza.", precio: 9.50, stock: 45 },
  { id: 19, nombre: "Gerbera rosa", imagen: "img/gerbera_rosa.jpg", descripcion: "Flor alegre y colorida con pétalos rosa intenso, perfecta para decorar cualquier ocasión.", precio: 11.00, stock: 25 },
  { id: 20, nombre: "Flor de loto", imagen: "img/flor_de_loto.jpg", descripcion: "Flor mística y elegante de pétalos suaves en tonos pastel, símbolo de pureza y espiritualidad.", precio: 25.00, stock: 10 },
  { id: 21, nombre: "Anémona púrpura", imagen: "img/anemona_purpura.jpg", descripcion: "Flor delicada de color púrpura con un centro oscuro, ideal para arreglos románticos.", precio: 14.00, stock: 20 },
  { id: 22, nombre: "Fresia blanca", imagen: "img/fresia_blanca.jpg", descripcion: "Flor pequeña y fragante con pétalos blancos, ideal para ramos de novia y decoraciones.", precio: 12.50, stock: 35 },
  { id: 23, nombre: "Zinnia naranja", imagen: "img/zinnia_naranja.jpg", descripcion: "Flor vibrante con pétalos de color naranja, perfecta para decoraciones alegres.", precio: 9.00, stock: 30 },
  { id: 24, nombre: "Caléndula", imagen: "img/calendula.jpg", descripcion: "Flor medicinal con pétalos de color naranja brillante, conocida por sus propiedades curativas.", precio: 8.00, stock: 50 },
  { id: 25, nombre: "Campanilla azul", imagen: "img/campanilla_azul.jpg", descripcion: "Flor pequeña y delicada con pétalos azul claro, ideal para jardines y arreglos florales.", precio: 7.50, stock: 40 },
  { id: 26, nombre: "Gladiolo rojo", imagen: "img/gladiolo_rojo.jpg", descripcion: "Flor alta y majestuosa con pétalos rojos vibrantes, ideal para eventos formales.", precio: 15.00, stock: 18 },
  { id: 27, nombre: "Flor de cerezo", imagen: "img/flor_de_cerezo.jpg", descripcion: "Flor delicada de color rosa suave, símbolo de la primavera y la renovación.", precio: 10.00, stock: 25 },
  { id: 28, nombre: "Narciso amarillo", imagen: "img/narciso_amarillo.jpg", descripcion: "Flor de pétalos amarillos brillantes, símbolo de esperanza y nuevos comienzos.", precio: 8.50, stock: 30 },
  { id: 29, nombre: "Alegría del hogar", imagen: "img/alegria_del_hogar.jpg", descripcion: "Flor pequeña y colorida, perfecta para alegrar interiores con su vibrante belleza.", precio: 6.00, stock: 45 },
  { id: 30, nombre: "Verbena morada", imagen: "img/verbena_morada.jpg", descripcion: "Flor pequeña y aromática con pétalos morados, ideal para jardines y decoraciones exteriores.", precio: 7.00, stock: 50 }
  ];

  